Update short-term-memory.mdx (#913)
when i run this example code ,raise a Exception like this:
```python
ValueError: Checkpointer requires one or more of the following 'configurable' 
keys: thread_id, checkpoint_ns, checkpoint_idValueError:
 Checkpointer requires one or more of the following 'configurable' keys: thread_id, checkpoint_ns, checkpoint_id
```
 so i add  `configurable` param

Co-authored-by: Eugene Yurtsev <eugene@langchain.dev>